//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 09:44:31 AM EDT 
//


package org.aeronomos.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interval-between-beats-msecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="generate-heartbeat" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intervalBetweenBeatsMsecs",
    "generateHeartbeat"
})
@XmlRootElement(name = "heartbeat-configuration", namespace = "http://model.aeronomos.org/configuration")
public class HeartbeatConfiguration {

    @XmlElement(name = "interval-between-beats-msecs", namespace = "http://model.aeronomos.org/configuration")
    protected int intervalBetweenBeatsMsecs;
    @XmlElement(name = "generate-heartbeat", namespace = "http://model.aeronomos.org/configuration")
    protected boolean generateHeartbeat;

    /**
     * Gets the value of the intervalBetweenBeatsMsecs property.
     * 
     */
    public int getIntervalBetweenBeatsMsecs() {
        return intervalBetweenBeatsMsecs;
    }

    /**
     * Sets the value of the intervalBetweenBeatsMsecs property.
     * 
     */
    public void setIntervalBetweenBeatsMsecs(int value) {
        this.intervalBetweenBeatsMsecs = value;
    }

    /**
     * Gets the value of the generateHeartbeat property.
     * 
     */
    public boolean isGenerateHeartbeat() {
        return generateHeartbeat;
    }

    /**
     * Sets the value of the generateHeartbeat property.
     * 
     */
    public void setGenerateHeartbeat(boolean value) {
        this.generateHeartbeat = value;
    }

}
