//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 09:44:31 AM EDT 
//


package org.aeronomos.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messaging-port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="messaging-transport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="messaging-host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messagingPort",
    "messagingTransport",
    "messagingHost"
})
@XmlRootElement(name = "messaging-configuration", namespace = "http://model.aeronomos.org/configuration")
public class MessagingConfiguration {

    @XmlElement(name = "messaging-port", namespace = "http://model.aeronomos.org/configuration")
    protected int messagingPort;
    @XmlElement(name = "messaging-transport", namespace = "http://model.aeronomos.org/configuration", required = true)
    protected String messagingTransport;
    @XmlElement(name = "messaging-host", namespace = "http://model.aeronomos.org/configuration", required = true)
    protected String messagingHost;

    /**
     * Gets the value of the messagingPort property.
     * 
     */
    public int getMessagingPort() {
        return messagingPort;
    }

    /**
     * Sets the value of the messagingPort property.
     * 
     */
    public void setMessagingPort(int value) {
        this.messagingPort = value;
    }

    /**
     * Gets the value of the messagingTransport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessagingTransport() {
        return messagingTransport;
    }

    /**
     * Sets the value of the messagingTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessagingTransport(String value) {
        this.messagingTransport = value;
    }

    /**
     * Gets the value of the messagingHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessagingHost() {
        return messagingHost;
    }

    /**
     * Sets the value of the messagingHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessagingHost(String value) {
        this.messagingHost = value;
    }

}
