//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 09:44:31 AM EDT 
//


package org.aeronomos.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.aeronomos.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Customer_QNAME = new QName("", "customer");
    private final static QName _MessageControlBlock_QNAME = new QName("http://model.aeronomos.org/common-types", "messageControlBlock");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.aeronomos.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HeartbeatConfiguration }
     * 
     */
    public HeartbeatConfiguration createHeartbeatConfiguration() {
        return new HeartbeatConfiguration();
    }

    /**
     * Create an instance of {@link MessageControlBlock }
     * 
     */
    public MessageControlBlock createMessageControlBlock() {
        return new MessageControlBlock();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link ScenarioConfiguratoin }
     * 
     */
    public ScenarioConfiguratoin createScenarioConfiguratoin() {
        return new ScenarioConfiguratoin();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link MessagingConfiguration }
     * 
     */
    public MessagingConfiguration createMessagingConfiguration() {
        return new MessagingConfiguration();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link RemoveUserRequest }
     * 
     */
    public RemoveUserRequest createRemoveUserRequest() {
        return new RemoveUserRequest();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customer")
    public JAXBElement<Customer> createCustomer(Customer value) {
        return new JAXBElement<Customer>(_Customer_QNAME, Customer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageControlBlock }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://model.aeronomos.org/common-types", name = "messageControlBlock")
    public JAXBElement<MessageControlBlock> createMessageControlBlock(MessageControlBlock value) {
        return new JAXBElement<MessageControlBlock>(_MessageControlBlock_QNAME, MessageControlBlock.class, null, value);
    }

}
