//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 09:44:31 AM EDT 
//


package org.aeronomos.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uuid" type="{http://model.aeronomos.org/common-types}UUIDType"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logicalStartTimeMSecs" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultDurationWithinStartupProtocolMSecs" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="durationFederationExecutionMSecs" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *       &lt;attribute name="durationToWaitForJoinSimulationResponseMSecs" type="{http://www.w3.org/2001/XMLSchema}long" default="5000" />
 *       &lt;attribute name="durationToWaitForRegisterSubscriptionResponseMSecs" type="{http://www.w3.org/2001/XMLSchema}long" default="5000" />
 *       &lt;attribute name="durationToWaitForRegisterToRunResponseMSecs" type="{http://www.w3.org/2001/XMLSchema}long" default="5000" />
 *       &lt;attribute name="durationToWaitForStartSimulationDirectiveMSecs" type="{http://www.w3.org/2001/XMLSchema}long" default="5000" />
 *       &lt;attribute name="durationToWaitAfterTerminationMSecs" type="{http://www.w3.org/2001/XMLSchema}long" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uuid",
    "name",
    "logicalStartTimeMSecs",
    "description",
    "defaultDurationWithinStartupProtocolMSecs",
    "durationFederationExecutionMSecs"
})
@XmlRootElement(name = "scenario-configuratoin", namespace = "http://model.aeronomos.org/configuration")
public class ScenarioConfiguratoin {

    @XmlElement(namespace = "http://model.aeronomos.org/configuration", required = true)
    protected String uuid;
    @XmlElement(namespace = "http://model.aeronomos.org/configuration", required = true)
    protected String name;
    @XmlElement(namespace = "http://model.aeronomos.org/configuration")
    protected long logicalStartTimeMSecs;
    @XmlElement(namespace = "http://model.aeronomos.org/configuration", required = true)
    protected String description;
    @XmlElement(namespace = "http://model.aeronomos.org/configuration", defaultValue = "5000")
    protected long defaultDurationWithinStartupProtocolMSecs;
    @XmlElement(namespace = "http://model.aeronomos.org/configuration", defaultValue = "60000")
    protected long durationFederationExecutionMSecs;
    @XmlAttribute(name = "durationToWaitForJoinSimulationResponseMSecs")
    protected Long durationToWaitForJoinSimulationResponseMSecs;
    @XmlAttribute(name = "durationToWaitForRegisterSubscriptionResponseMSecs")
    protected Long durationToWaitForRegisterSubscriptionResponseMSecs;
    @XmlAttribute(name = "durationToWaitForRegisterToRunResponseMSecs")
    protected Long durationToWaitForRegisterToRunResponseMSecs;
    @XmlAttribute(name = "durationToWaitForStartSimulationDirectiveMSecs")
    protected Long durationToWaitForStartSimulationDirectiveMSecs;
    @XmlAttribute(name = "durationToWaitAfterTerminationMSecs")
    protected Long durationToWaitAfterTerminationMSecs;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the logicalStartTimeMSecs property.
     * 
     */
    public long getLogicalStartTimeMSecs() {
        return logicalStartTimeMSecs;
    }

    /**
     * Sets the value of the logicalStartTimeMSecs property.
     * 
     */
    public void setLogicalStartTimeMSecs(long value) {
        this.logicalStartTimeMSecs = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the defaultDurationWithinStartupProtocolMSecs property.
     * 
     */
    public long getDefaultDurationWithinStartupProtocolMSecs() {
        return defaultDurationWithinStartupProtocolMSecs;
    }

    /**
     * Sets the value of the defaultDurationWithinStartupProtocolMSecs property.
     * 
     */
    public void setDefaultDurationWithinStartupProtocolMSecs(long value) {
        this.defaultDurationWithinStartupProtocolMSecs = value;
    }

    /**
     * Gets the value of the durationFederationExecutionMSecs property.
     * 
     */
    public long getDurationFederationExecutionMSecs() {
        return durationFederationExecutionMSecs;
    }

    /**
     * Sets the value of the durationFederationExecutionMSecs property.
     * 
     */
    public void setDurationFederationExecutionMSecs(long value) {
        this.durationFederationExecutionMSecs = value;
    }

    /**
     * Gets the value of the durationToWaitForJoinSimulationResponseMSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDurationToWaitForJoinSimulationResponseMSecs() {
        if (durationToWaitForJoinSimulationResponseMSecs == null) {
            return  5000L;
        } else {
            return durationToWaitForJoinSimulationResponseMSecs;
        }
    }

    /**
     * Sets the value of the durationToWaitForJoinSimulationResponseMSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDurationToWaitForJoinSimulationResponseMSecs(Long value) {
        this.durationToWaitForJoinSimulationResponseMSecs = value;
    }

    /**
     * Gets the value of the durationToWaitForRegisterSubscriptionResponseMSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDurationToWaitForRegisterSubscriptionResponseMSecs() {
        if (durationToWaitForRegisterSubscriptionResponseMSecs == null) {
            return  5000L;
        } else {
            return durationToWaitForRegisterSubscriptionResponseMSecs;
        }
    }

    /**
     * Sets the value of the durationToWaitForRegisterSubscriptionResponseMSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDurationToWaitForRegisterSubscriptionResponseMSecs(Long value) {
        this.durationToWaitForRegisterSubscriptionResponseMSecs = value;
    }

    /**
     * Gets the value of the durationToWaitForRegisterToRunResponseMSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDurationToWaitForRegisterToRunResponseMSecs() {
        if (durationToWaitForRegisterToRunResponseMSecs == null) {
            return  5000L;
        } else {
            return durationToWaitForRegisterToRunResponseMSecs;
        }
    }

    /**
     * Sets the value of the durationToWaitForRegisterToRunResponseMSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDurationToWaitForRegisterToRunResponseMSecs(Long value) {
        this.durationToWaitForRegisterToRunResponseMSecs = value;
    }

    /**
     * Gets the value of the durationToWaitForStartSimulationDirectiveMSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDurationToWaitForStartSimulationDirectiveMSecs() {
        if (durationToWaitForStartSimulationDirectiveMSecs == null) {
            return  5000L;
        } else {
            return durationToWaitForStartSimulationDirectiveMSecs;
        }
    }

    /**
     * Sets the value of the durationToWaitForStartSimulationDirectiveMSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDurationToWaitForStartSimulationDirectiveMSecs(Long value) {
        this.durationToWaitForStartSimulationDirectiveMSecs = value;
    }

    /**
     * Gets the value of the durationToWaitAfterTerminationMSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDurationToWaitAfterTerminationMSecs() {
        if (durationToWaitAfterTerminationMSecs == null) {
            return  1L;
        } else {
            return durationToWaitAfterTerminationMSecs;
        }
    }

    /**
     * Sets the value of the durationToWaitAfterTerminationMSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDurationToWaitAfterTerminationMSecs(Long value) {
        this.durationToWaitAfterTerminationMSecs = value;
    }

}
